version: '3.2'

services:

  app:
    image: ghcr.io/mjpinto-stefanini/php81-fpm:latest
    labels:
      - traefik.http.routers.gandauth.rule=Host(`gandauth.stefanini.test`)
    volumes:
      - ./src:/src
    environment:
      - PROJECT_WEBROOT=/src/public
    #ports:
    #  - '5173:5173'

  oraclegandauth:
    image: wnameless/oracle-xe-11g-r2
    labels:
    - traefik.http.routers.oracle-gandauth.rule=Host(`oracle-gandauth.test`)
    environment:
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1523:1521"
      - "5502:5500"
    networks:
      - default

networks:
  default:
    external:
      name: dev-network